const samples = [
  "Just finished my midterm exams and feeling pretty good about them! Can't wait for the weekend to relax 😊",
  "Just finished my midterm and I think I aced it! Feeling proud of myself 💪",
  "Does anyone want to form a study group for the upcoming project in Econ 101? Let me know!",
  "The line at the campus coffee shop is insane right now ☕",
  "How is everyone feeling as we approach the end of the semester? Hang in there, we've got this!",
  "Loving the fall colors on campus right now 🍁",
  "The library is my second home during midterms 😅",
  "Can't believe how fast this semester is going by! Time flies when you're studying, I guess.",
  "Just discovered a new study spot on campus and I'm never leaving!",
  "Anyone else excited for the upcoming football game? Go team! 🏈",
  "Campus feels so empty during early morning classes.",
  "The Wi-Fi on campus has been so slow lately, it's driving me crazy!",
  "Campus squirrels are getting bolder by the day, I swear they're planning something.",
  "Finally got to visit the new science building - it's so modern compared to the others!",
  "Not sure if I can handle another group project this semester... 😩",
  "Who else is counting down the days until the semester break?",
  "The struggle of finding a parking spot on campus is real.",
  "Just want to give a shoutout to the campus janitorial staff for keeping everything clean and tidy!",
  "Feeling the pressure with all these assignments due at the same time.",
  "Campus events always make my week more interesting!",
  "The sunset view from the campus rooftop is absolutely stunning.",
  "Feeling the stress of midterms already, anyone else? 😩📚",
  "Can we talk about how long the lines are at the on-campus coffee shop? I just want my caffeine fix, is that too much to ask? ☕",
  "Did anyone see that squirrel steal someone's sandwich near the quad? Nature is wild, man. 🐿️🥪",
  "I'll pay someone in meal swipes to let me join their study group for the upcoming exam. Help a struggling soul out! 📝📚",
  "The Wi-Fi in the library is so spotty, it's like playing a game of chance every time I try to submit an assignment. 🎲💻",
  "Thinking of starting a petition to get more comfortable chairs in the lecture halls. My butt can't handle these rock-hard seats anymore. 🪑😫",
  "I swear, finding a parking spot on campus is more challenging than some of my classes. 🅿️🤦‍♂️",
  "Honestly, the campus ducks have more attitude than most people I know. 🦆💁‍♂️",
  "Can we have a moment of silence for all the fallen laptop chargers that couldn't survive the semester? 🙏💻🔌",
  "Is it just me or does it feel like there’s construction happening on campus 24/7? 🔨🚧",
  "I miss the days when my biggest problem was deciding what to eat at the dining hall, now it's all about deadlines and grades. 🍔📚",
  "The struggle of finding a free outlet in the library is so real, it's like a game of musical chairs but with chargers. 🔌🪑🎶",
  "I thought college would be all about profound intellectual conversations, but most days I hear debates about where to get the best cheap eats. 🌮🤔",
  "Campus squirrels are evolving, I saw one turn a door handle like it owned the place. 🐿️🚪",
  "Just once, I want to walk into the math building and not feel like I'm stepping into another dimension. 🔢🌀",
  "Do you ever look at your packed schedule and just wonder how you're going to survive the semester? Yeah, me too. 😅📅",
  "I miss the days when recess was a thing, now my only break between classes is power-walking to avoid being late. 🏃‍♂️⏰",
  "Can we all agree that the struggle of carrying 5 textbooks to class is way too real? My back can't handle much more of this. 📚😫",
  "I never realized how much I took nap time for granted until college hit me like a ton of bricks. 💤🧱",
  "Sometimes I wonder if the campus geese are secretly plotting to take over the world. 🦢🌍",
  "Hey y'all, can we talk about how confusing the new campus layout is? I feel like I discover a new building every week 😅",
  "Is anyone down to start a study group for the upcoming exams? I definitely need all the help I can get.",
  "I swear if the cafeteria serves one more soggy sandwich, I'm gonna riot 🙄",
  "Is it just me or is the Wi-Fi on campus getting worse by the day? It's like a game of roulette trying to get a good connection.",
  "Does anyone know if the library is open late during finals week? I need a quiet place to cram until midnight.",
  "Who else is feeling the struggle of midterms already? 📚😩",
  "Anyone down to hit up the library with me later? Need some motivation to study 😅",
  "Can we talk about how long the lines at the coffee shop are right now? ☕️🙃",
  "Low-key tempted to just skip class and nap in the quad instead 😴🌳",
  "Just discovered the hidden gem study spot in the basement of the engineering building - no one knows about it! 🤫📝",
  "Is it just me or does the Wi-Fi keep acting up everywhere on campus? 📶😠",
  "Feeling like all I do is eat, sleep, study, repeat. Can't wait for the weekend already! 🍕💤📚",
  "Anyone else think the new art exhibit in the student center is kinda meh? 🎨🤔",
  "The struggle of finding an open plug in the library during finals week is real. 🔌😫",
  "Honestly considering joining a study group just for the free snacks they always seem to have 🍪📚",
  "Why does it feel like every professor decided to schedule a test for the same week? 🤯📝",
  "Can we take a moment to appreciate how amazing the fall foliage on campus looks right now? 🍁🍂✨",
  "Campus feels so empty during summer break, kinda spooky walking around alone at night 👻🌙",
  "Just witnessed someone try to skateboard down the main walkway and wipe out spectacularly. Made my day 😂🛹",
  "The struggle of finding a parking spot on campus is too real today. Been circling for ages! 🅿️🚗",
  "Trying to get through this 8 a.m. class like ☕️☕️☕️💤",
  "The line at the food truck by the quad is worth the wait, trust me. Those tacos are 🔥🌮",
  "Lmk if anyone's up for a late-night study session at the library - caffeine and company would be much appreciated! 🌃📚☕️",
  "Can't decide if I love or hate the new setup at the gym... it's confusing af 🏋️‍♂️🤔",
  "Bracing myself for the inevitable chaos that is registration week. May the odds be ever in our favor 🤞💻📆",
  "Hey everyone, hope your classes are going well so far! Has anyone tried the new coffee shop near the library? ☕",
  "Anyone up for forming a study group for the upcoming midterm in Econ 101? Let's ace this together!",
  "The gym has been super crowded lately - looks like everyone's keeping up with their fitness goals this semester!💪",
  "I heard there's a food truck festival happening on campus next week, who's excited to indulge in some yummy treats?🍔🍕",
  "The line at the bookstore was insane today - did they restock on supplies or something?",
  "Hey y'all, anyone up for forming a study group for the upcoming midterm in the library? 📚",
  "Damn, the Wi-Fi in the dorms has been so spotty lately. Can't deal with these disconnections during online lectures. 📶",
  "Has anyone checked out the new food truck near the quad? Their tacos are seriously legit! 🌮",
  "I heard they're renovating the science building next semester. About time, that place was falling apart. 🔨",
  "The gym has been packed lately, everyone must be getting their summer body ready early! 🏋️‍♂️",
  "I'll be chilling in the student center if anyone wants to join me for some coffee and procrastination ☕️",
  "The line at the bookstore is a nightmare right now, avoid it if you can! 📚",
  "I can't believe they're finally opening up that new lounge in the business building tomorrow. Perfect spot to de-stress between classes. 🛋️",
  "The squirrels on campus have been extra bold lately, almost snatched a fry right out of my hand yesterday! 🐿️",
  "I swear every time I try to park near the dorms, there's never any spots left. Guess I'll be walking from now on. 🅿️",
  "The weather has been so unpredictable lately, make sure to carry an umbrella with you at all times! ☔",
  "I can't be the only one struggling with the 8 a.m. classes, right? It's a whole mood trying to stay awake. 😴",
  "Does anyone know if the student health center is still doing free flu shots? Need to get myself protected ASAP! 💉",
  "The engineering lab is always freezing, I swear they're trying to turn us into icicles in there. ❄️",
  "I'm this close 👌 to dropping this one class, the professor is just on another level of boring. 💤",
  "The art exhibit in the campus gallery is honestly stunning, y'all should check it out if you haven't already. 🎨",
  "That group project for history is giving me a headache, why is it so hard to coordinate schedules with everyone? 📅",
  "The campus cat blessed me with its presence on the way to class today, it's going to be a good day. 🐱",
  "I don't know who needs to hear this, but please clean up after yourselves in the library. It's not that hard! 🚮",
];
